version: 1.1.2

cache: true

registration:
  socialLogins: ["github", "google"]

endpoints:
  custom:
      
    # groq
    - name: "groq"
      apiKey: "${GROQ_API_KEY}"
      baseURL: "https://api.groq.com/openai/v1/"
      models:
        default: [
          "llama-3.2-3b-preview",
          "llama3-70b-8192",
          "llama3-8b-8192",
          "mixtral-8x7b-32768",
          "gemma2-9b-it",
          "gemma-7b-it",
          ]
        fetch: false
      titleConvo: true
      titleModel: "mixtral-8x7b-32768"
      modelDisplayLabel: "groq"
      
    # Mistral AI API
    - name: "Mistral"
      apiKey: "${MISTRAL_API_KEY}"
      baseURL: "https://api.mistral.ai/v1"
      models: 
        default: [
          "mistral-tiny",
          "mistral-small",
          "mistral-medium",
          "mistral-large-latest"
          ]
        fetch: false
      titleConvo: true
      titleMethod: "completion"
      titleModel: "mistral-tiny"
      summarize: false
      summaryModel: "mistral-tiny"
      forcePrompt: false
      modelDisplayLabel: "Mistral"
      dropParams: ["stop", "user", "frequency_penalty", "presence_penalty"]


    # # OpenRouter.ai - Perplexity
    # - name: "OpenRouter-Perplexity"
    #   apiKey: "${OPENROUTER_KEY}"
    #   baseURL: "https://openrouter.ai/api/v1"
    #   models:
    #     "default": [
    #       "perplexity/pplx-7b-chat",
    #       "perplexity/pplx-70b-chat",
    #       "perplexity/pplx-7b-online",
    #       "perplexity/pplx-70b-online",
    #       "perplexity/sonar-medium-online",
    #       ]
    #     fetch: false
    #   titleConvo: true
    #   titleModel: "perplexity/pplx-7b-chat"
    #   summarize: false
    #   summaryModel: "perplexity/pplx-7b-chat"
    #   forcePrompt: false
    #   dropParams: ["stop"]
    #   modelDisplayLabel: "Perplexity"
    #   iconURL: "https://raw.githubusercontent.com/fuegovic/lc-config-yaml/main/icons/perplexityai.png"

    - name: "Perplexity"
      apiKey: "${PERPLEXITY_API_KEY}"
      baseURL: "https://api.perplexity.ai/"
      models:
        default: [
          "mistral-7b-instruct",
          "sonar-small-chat",
          "sonar-small-online",
          "sonar-medium-chat",
          "sonar-medium-online"
          ]
        fetch: false # fetching list of models is not supported
      titleConvo: true
      titleModel: "sonar-medium-chat"
      summarize: false
      summaryModel: "sonar-medium-chat"
      forcePrompt: false
      dropParams: ["stop", "frequency_penalty"]
      modelDisplayLabel: "Perplexity"
